openapi: "3.0.0"
info:
  version: 1.0.0
  title: Client Service
servers:
  - url: http://localhost:8081
paths:
  /default:
    get:
      summary: Default message
      responses:
        '200':
          description: Default message

components:
  schemas:
    Client:
      required:
        - name
        - lastName
        - type
        - birthdate
      type: object
      properties:
        id:
          type: string
          example: "843un884931019rj10932"
        document:
          type: string
          example: "12345678"
        name:
          type: string
          example: Rafael
        lastName:
          type: string
          example: Ponte
        address:
          type: string
          example: Lima - Perú
        phone:
          type: string
          example: '987654321'
        birthDate:
          type: string
        type:
          type: string
          enum:
            - personal
            - business
        profile:
          type: string
          enum:
            - vip
            - pyme

    ModelApiResponse:
      type: object
      properties:
        status:
          type: integer
          description: HTTP status code of the response
        message:
          type: string
          description: Message for the response
        data:
          type: object
          description: Data for the response