server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: gateway
          uri: https://github.com/RafaelAnderson/Microservice-Config
  application:
    name: config-server